services:
  api:
    environment:
      APP_ENV: dev
      WECHAT_APPID: ""
      WECHAT_SECRET: ""
      OSS_BACKEND: mock
      MOCK_OSS_ENABLED: "true"
      OSS_BUCKET: photo-agent-dev
      OSS_KEY_ID: LTAI_xxx
      OSS_KEY_SECRET: xxx
      DASHSCOPE_API_KEY: sk-xxx
      OPENAI_API_KEY: sk-openai-xxx

  worker:
    environment:
      APP_ENV: dev
      WECHAT_APPID: ""
      WECHAT_SECRET: ""
      OSS_BACKEND: mock
      MOCK_OSS_ENABLED: "true"
      OSS_BUCKET: photo-agent-dev
      OSS_KEY_ID: LTAI_xxx
      OSS_KEY_SECRET: xxx
      DASHSCOPE_API_KEY: sk-xxx
      OPENAI_API_KEY: sk-openai-xxx
