/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 存活检查（K8s liveness）
         * @description 仅证明 API 进程能响应，不访问外部依赖。
         */
        get: operations["live_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 就绪检查（K8s readiness）
         * @description 数据库和 Redis 均可用时才允许实例接收业务流量。
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/wechat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 小程序 code 换 JWT */
        post: operations["wechat_login_auth_wechat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户信息（用于 JWT 联调） */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 申请 OSS 直传签名 URL
         * @description 工作流：
         *     1. 若同用户同 hash 的照片已存在，直接返回 duplicate=true，客户端可跳过 PUT；
         *     2. 否则生成 OSS 直传签名 URL（PUT 方法，Content-Type 已绑定），
         *        并把客户端必须回带的 header 也一并告诉它。
         */
        post: operations["get_upload_url_photos_upload_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 时间线：分页拉取当前用户照片 */
        get: operations["list_photos_photos_get"];
        put?: never;
        /** 上传完成回调（后端会去 OSS 核验对象真的存在） */
        post: operations["create_photo_photos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/processing-status/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 批量轮询照片处理和智能搜索索引状态
         * @description 仅返回属于当前用户的照片；不存在或越权 ID 不回显。
         */
        post: operations["batch_processing_status_photos_processing_status_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{photo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 照片详情 */
        get: operations["get_photo_photos__photo_id__get"];
        put?: never;
        post?: never;
        /** 删除照片 */
        delete: operations["delete_photo_photos__photo_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{photo_id}/processing-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 轮询单张照片处理和智能搜索索引状态 */
        get: operations["get_processing_status_photos__photo_id__processing_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{photo_id}/retry-search-index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手动重试已经耗尽或入队失败的智能搜索索引 */
        post: operations["retry_search_index_photos__photo_id__retry_search_index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{photo_id}/interact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上报用户与单张照片的交互行为
         * @description 前端在查看/收藏/分享/下载照片时调用，写入 photo_interact 事件。
         */
        post: operations["report_photo_interact_photos__photo_id__interact_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 按自然语言语义搜索（支持时间/标签/游标/自动解析） */
        post: operations["semantic_search_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/click": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上报用户点击了某条搜索结果
         * @description 前端在用户点击搜索结果卡片时调用，写入 search_click 事件。
         */
        post: operations["report_search_click_search_click_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/album-fallback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 智能全量相册兜底（语义+新鲜度+个性化排序）
         * @description 当普通搜索无结果时，返回用户全量相册的智能排序结果。
         */
        post: operations["album_fallback_search_album_fallback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的 Skill 列表（含官方 + 我自建） */
        get: operations["list_my_skills_skills_get"];
        put?: never;
        /** 创建自定义 Skill */
        post: operations["create_skill_skills_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/plaza": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 广场：公开的用户 Skill + 官方 Skill */
        get: operations["plaza_skills_plaza_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/{skill_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Skill 详情 */
        get: operations["get_skill_skills__skill_id__get"];
        put?: never;
        post?: never;
        /** 删除我的 Skill */
        delete: operations["delete_skill_skills__skill_id__delete"];
        options?: never;
        head?: never;
        /** 修改我的 Skill */
        patch: operations["update_skill_skills__skill_id__patch"];
        trace?: never;
    };
    "/skills/_/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 今日剩余免费生成次数 */
        get: operations["my_quota_skills___quota_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 运行 Photo Agent（支持新建/续接会话）
         * @description 用户输入一条自然语言请求，Agent 决定搜索、澄清或生成。
         *
         *     - 不带 session_id：新建会话；
         *     - 带 session_id：续接之前会话，保留搜索历史、已澄清次数、兜底级别等状态。
         *
         *     同一用户的并发请求会被 Redis 分布式锁串行化，避免状态混乱。
         */
        post: operations["agent_run_agent_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 流式运行 Photo Agent（SSE，实时推送思考/工具调用/结果）
         * @description 与 /run 相同语义，但事件通过 Server-Sent Events 实时推送。
         *
         *     事件格式（每行一个 SSE 数据帧）：
         *       data: {"type": "start", "payload": {...}, "step": 0}
         *
         *
         *     前端可用 EventSource 接收并渲染：
         *       - start: 任务开始
         *       - route: 当前轮次的意图与上下文关系（new/replace/refine/continue）
         *       - think: 复杂请求进入 Agent 后的 LLM 思考过程
         *       - tool_call / tool_result: 工具调用与结果
         *       - clarify: 需要用户澄清
         *       - final: 最终回复
         *       - done: 会话结束，payload 包含 session_id 与最终 status
         *
         *     同一用户的并发请求会被 Redis 分布式锁串行化。
         */
        post: operations["agent_stream_agent_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{photo_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用 Skill 对某张照片做 AI 改造（异步） */
        post: operations["create_generation_photos__photo_id__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generations/{generation_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 确认并入队生成任务（可幂等重试） */
        post: operations["confirm_generation_route_generations__generation_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的生成历史 */
        get: operations["list_my_generations_generations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generations/{generation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 生成任务详情（用于轮询状态） */
        get: operations["get_generation_generations__generation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新所有配置（热更新）
         * @description 触发全量配置热刷新.
         *
         *     包括:
         *     - Skill注册表（从DB重新加载）
         *     - Prompt注册表（从配置文件重新加载）
         *
         *     刷新过程:
         *     1. 获取全局锁，防止并发刷新
         *     2. 构建新数据
         *     3. 原子替换引用（进行中的请求不受影响）
         */
        post: operations["refresh_config_admin_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/refresh/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新Skill注册表
         * @description 单独刷新Skill注册表.
         */
        post: operations["refresh_skills_admin_refresh_skills_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/refresh/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新Prompt注册表
         * @description 单独刷新Prompt注册表.
         */
        post: operations["refresh_prompts_admin_refresh_prompts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查看注册表状态
         * @description 查看所有注册表当前状态（用于监控）.
         */
        get: operations["registry_stats_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentRunRequest
         * @description 运行 Agent 的请求。
         */
        AgentRunRequest: {
            /** Query */
            query: string;
            /**
             * Session Id
             * @description 续接已有会话 ID
             */
            session_id?: string | null;
            /**
             * Selected Photo Id
             * @description 用户在当前候选列表中明确点击选择的照片 ID
             */
            selected_photo_id?: string | null;
        };
        /**
         * AgentRunResponse
         * @description Agent 运行结果。
         */
        AgentRunResponse: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Events */
            events: Record<string, never>[];
            /** State */
            state: Record<string, never>;
            /** Status */
            status: string;
        };
        /**
         * AlbumFallbackQuery
         * @description 智能全量相册兜底查询：无严格过滤，按语义+新鲜度+个性化综合排序。
         */
        AlbumFallbackQuery: {
            /** Q */
            q?: string | null;
            /**
             * Limit
             * @default 20
             */
            limit: number;
            /** Cursor */
            cursor?: string | null;
            /**
             * W Semantic
             * @default 0.4
             */
            w_semantic: number;
            /**
             * W Recency
             * @default 0.35
             */
            w_recency: number;
            /**
             * W Interaction
             * @default 0.25
             */
            w_interaction: number;
        };
        /** GenerateRequest */
        GenerateRequest: {
            /** Skill Id */
            skill_id?: string | null;
            /** Extra Prompt */
            extra_prompt?: string | null;
            /** Model */
            model?: string | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /** GenerationConfirmRequest */
        GenerationConfirmRequest: {
            /**
             * Confirmation Token
             * Format: uuid
             */
            confirmation_token: string;
        };
        /** GenerationOut */
        GenerationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Photo Id */
            source_photo_id: string | null;
            /** Skill Id */
            skill_id: string | null;
            /** Extra Prompt */
            extra_prompt: string | null;
            /** Result Oss Key */
            result_oss_key: string | null;
            /** Result Url */
            result_url?: string | null;
            /** Status */
            status: string;
            /** Error Message */
            error_message: string | null;
            /** Model */
            model: string;
            /** Cost Yuan */
            cost_yuan: string;
            /**
             * Estimated Cost Yuan
             * @default 0
             */
            estimated_cost_yuan: string;
            /** Confirmation Token */
            confirmation_token?: string | null;
            /** Confirmation Expires At */
            confirmation_expires_at?: string | null;
            /**
             * Enqueue Status
             * @default not_queued
             */
            enqueue_status: string;
            /**
             * Attempt Count
             * @default 0
             */
            attempt_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description 小程序 wx.login() 拿到的临时 code.
         */
        LoginRequest: {
            /**
             * Code
             * @description wx.login code
             */
            code: string;
            /** Nickname */
            nickname?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
        };
        /**
         * ParsedQuery
         * @description query_parser 拆解后的结构化条件。留白位可以让 auto_parse=True 时生效。
         */
        ParsedQuery: {
            /** Semantic */
            semantic: string;
            /** From Date */
            from_date?: string | null;
            /** To Date */
            to_date?: string | null;
            /** Place */
            place?: string | null;
            /** Tags */
            tags?: string[];
        };
        /** PhotoCreate */
        PhotoCreate: {
            /** Oss Key */
            oss_key: string;
            /** Hash */
            hash: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Mime Type
             * @default image/jpeg
             */
            mime_type: string;
        };
        /**
         * PhotoInteract
         * @description 前端上报用户与单张照片的交互行为。
         */
        PhotoInteract: {
            /** Action */
            action: string;
            /** Context */
            context?: string | null;
        };
        /**
         * PhotoListItem
         * @description 时间线返回项，附带临时缩略图 URL.
         */
        PhotoListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Thumb Url */
            thumb_url?: string | null;
            /** Taken At */
            taken_at: string | null;
            /** Ai Description */
            ai_description: string | null;
            /** Status */
            status: string;
            /** Search Index Status */
            search_index_status: string;
            /** Search Index Message */
            search_index_message: string;
            /**
             * Embedding Retry Count
             * @default 0
             */
            embedding_retry_count: number;
            /**
             * Embedding Max Attempts
             * @default 5
             */
            embedding_max_attempts: number;
            /** Embedding Next Retry At */
            embedding_next_retry_at?: string | null;
        };
        /** PhotoOut */
        PhotoOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Oss Key */
            oss_key: string;
            /** Thumb Key */
            thumb_key: string | null;
            /** Taken At */
            taken_at: string | null;
            /** Ai Description */
            ai_description: string | null;
            /** Status */
            status: string;
            /** Search Index Status */
            search_index_status: string;
            /** Search Index Message */
            search_index_message: string;
            /**
             * Embedding Retry Count
             * @default 0
             */
            embedding_retry_count: number;
            /**
             * Embedding Max Attempts
             * @default 5
             */
            embedding_max_attempts: number;
            /** Embedding Next Retry At */
            embedding_next_retry_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PhotoProcessingStatus */
        PhotoProcessingStatus: {
            /**
             * Photo Id
             * Format: uuid
             */
            photo_id: string;
            /** Photo Status */
            photo_status: string;
            /** Search Index Status */
            search_index_status: string;
            /**
             * Retry Count
             * @default 0
             */
            retry_count: number;
            /**
             * Max Attempts
             * @default 5
             */
            max_attempts: number;
            /** Next Retry At */
            next_retry_at?: string | null;
            /** Next Retry In Seconds */
            next_retry_in_seconds?: number | null;
            /** Message */
            message: string;
        };
        /** PhotoProcessingStatusBatchRequest */
        PhotoProcessingStatusBatchRequest: {
            /** Photo Ids */
            photo_ids: string[];
        };
        /** PhotoProcessingStatusBatchResponse */
        PhotoProcessingStatusBatchResponse: {
            /** Items */
            items: components["schemas"]["PhotoProcessingStatus"][];
        };
        /** QuotaInfo */
        QuotaInfo: {
            /** Used */
            used: number;
            /** Quota */
            quota: number;
            /** Remaining */
            remaining: number;
        };
        /**
         * SearchClick
         * @description 前端上报用户点击了某条搜索结果。
         */
        SearchClick: {
            /**
             * Photo Id
             * Format: uuid
             */
            photo_id: string;
            /**
             * Query
             * @default
             */
            query: string;
            /**
             * Rank
             * @default 0
             */
            rank: number;
        };
        /**
         * SearchConstraintCheck
         * @description 强约束候选校验摘要；不暴露被过滤照片的内容。
         */
        SearchConstraintCheck: {
            /**
             * Applied
             * @default true
             */
            applied: boolean;
            /** Constraints */
            constraints?: {
                [key: string]: string;
            }[];
            /**
             * Candidates Checked
             * @default 0
             */
            candidates_checked: number;
            /**
             * Matched Count
             * @default 0
             */
            matched_count: number;
            /**
             * Rejected Count
             * @default 0
             */
            rejected_count: number;
            /** Rejected By Kind */
            rejected_by_kind?: {
                [key: string]: number;
            };
        };
        /** SearchIndexCoverage */
        SearchIndexCoverage: {
            /**
             * Total Photos
             * @default 0
             */
            total_photos: number;
            /**
             * Indexed Photos
             * @default 0
             */
            indexed_photos: number;
            /**
             * Retrying Photos
             * @default 0
             */
            retrying_photos: number;
            /**
             * Unavailable Photos
             * @default 0
             */
            unavailable_photos: number;
            /**
             * Coverage Ratio
             * @default 1
             */
            coverage_ratio: number;
            /** Message */
            message?: string | null;
            /**
             * Faceted Photos
             * @default 0
             */
            faceted_photos: number;
            /**
             * Facet Coverage Ratio
             * @default 1
             */
            facet_coverage_ratio: number;
            /**
             * Semantic Complete
             * @default true
             */
            semantic_complete: boolean;
            /** Semantic Message */
            semantic_message?: string | null;
        };
        /**
         * SearchQuery
         * @description 支持多维过滤 + 混合排序 + 游标分页。
         *
         *     示例：
         *       {"q":"雨天的猫", "from_date":"2026-07-01", "to_date":"2026-07-31",
         *        "tags":["小橘"], "limit":20}
         */
        SearchQuery: {
            /** Q */
            q: string;
            /**
             * Limit
             * @default 5
             */
            limit: number;
            /**
             * Result Mode
             * @default browse
             * @enum {string}
             */
            result_mode: "browse" | "best" | "select";
            /**
             * Complete Result Set
             * @description select 模式下扫描并返回全部符合硬条件的已索引照片
             * @default false
             */
            complete_result_set: boolean;
            /** From Date */
            from_date?: string | null;
            /** To Date */
            to_date?: string | null;
            /** Tags */
            tags?: string[] | null;
            /**
             * Status
             * @default done
             */
            status: string | null;
            /** Scene */
            scene?: string | null;
            /** Objects */
            objects?: string[] | null;
            /** Text In Image */
            text_in_image?: string[] | null;
            /** Mood */
            mood?: string | null;
            /** Colors */
            colors?: string[] | null;
            /** Photo Types */
            photo_types?: ("selfie" | "screenshot" | "group_photo" | "portrait" | "document" | "food" | "scenery" | "other")[] | null;
            /** Is Selfie */
            is_selfie?: boolean | null;
            /** People Count Min */
            people_count_min?: number | null;
            /** People Count Max */
            people_count_max?: number | null;
            /** Min Semantic Score */
            min_semantic_score?: number | null;
            /**
             * W Semantic
             * @default 0.7
             */
            w_semantic: number;
            /**
             * W Recency
             * @default 0.2
             */
            w_recency: number;
            /**
             * W Interaction
             * @default 0.1
             */
            w_interaction: number;
            /** Cursor */
            cursor?: string | null;
            /**
             * Auto Parse
             * @default false
             */
            auto_parse: boolean;
            /**
             * Verify Constraints
             * @default true
             */
            verify_constraints: boolean;
            /**
             * Verify Semantic
             * @default true
             */
            verify_semantic: boolean;
        };
        /**
         * SearchRerankCheck
         * @description Top-K 判同摘要；不返回被过滤候选的 ID 或图片内容。
         */
        SearchRerankCheck: {
            /**
             * Applied
             * @default true
             */
            applied: boolean;
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Degraded Reason */
            degraded_reason?: string | null;
            /** Prompt Version */
            prompt_version: string;
            /** Model */
            model?: string | null;
            /**
             * Candidates Checked
             * @default 0
             */
            candidates_checked: number;
            /**
             * Match Count
             * @default 0
             */
            match_count: number;
            /**
             * Uncertain Count
             * @default 0
             */
            uncertain_count: number;
            /**
             * Contradiction Count
             * @default 0
             */
            contradiction_count: number;
            /**
             * Rejected Count
             * @default 0
             */
            rejected_count: number;
            /**
             * Zero Match Filtered
             * @default false
             */
            zero_match_filtered: boolean;
            /**
             * Unjudged Filtered Count
             * @default 0
             */
            unjudged_filtered_count: number;
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /**
             * Visual Verification Applied
             * @default false
             */
            visual_verification_applied: boolean;
            /** Visual Prompt Version */
            visual_prompt_version?: string | null;
            /** Visual Trigger Reason */
            visual_trigger_reason?: string | null;
            /**
             * Visual Candidates Checked
             * @default 0
             */
            visual_candidates_checked: number;
            /**
             * Visual Match Count
             * @default 0
             */
            visual_match_count: number;
            /**
             * Visual Uncertain Count
             * @default 0
             */
            visual_uncertain_count: number;
            /**
             * Visual Contradiction Count
             * @default 0
             */
            visual_contradiction_count: number;
            /**
             * Visual Cache Hit
             * @default false
             */
            visual_cache_hit: boolean;
            /**
             * Visual Degraded
             * @default false
             */
            visual_degraded: boolean;
            /** Visual Degraded Reason */
            visual_degraded_reason?: string | null;
            /**
             * Visual Latency Ms
             * @default 0
             */
            visual_latency_ms: number;
        };
        /** SearchResult */
        SearchResult: {
            /** Items */
            items: components["schemas"]["SearchResultItem"][];
            /** Total */
            total: number;
            /**
             * Result Mode
             * @default browse
             * @enum {string}
             */
            result_mode: "browse" | "best" | "select";
            /**
             * Total Matches
             * @default 0
             */
            total_matches: number;
            /**
             * Result Set Complete
             * @default false
             */
            result_set_complete: boolean;
            /** Completeness Reason */
            completeness_reason?: string | null;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /** Next Cursor */
            next_cursor?: string | null;
            parsed?: components["schemas"]["ParsedQuery"] | null;
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
            constraint_check?: components["schemas"]["SearchConstraintCheck"] | null;
            rerank_check?: components["schemas"]["SearchRerankCheck"] | null;
            index_coverage?: components["schemas"]["SearchIndexCoverage"] | null;
            /** Similarity Threshold */
            similarity_threshold?: number | null;
            /**
             * Threshold Filtered Count
             * @default 0
             */
            threshold_filtered_count: number;
            /** Threshold Bypassed Reason */
            threshold_bypassed_reason?: string | null;
            /** Coverage Hint */
            coverage_hint?: string | null;
            /**
             * Semantic Facets Required
             * @default false
             */
            semantic_facets_required: boolean;
        };
        /** SearchResultItem */
        SearchResultItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Thumb Url */
            thumb_url?: string | null;
            /** Taken At */
            taken_at?: string | null;
            /** Ai Description */
            ai_description?: string | null;
            /** Status */
            status: string;
            /**
             * Score Semantic
             * @default 0
             */
            score_semantic: number;
            /**
             * Score Recency
             * @default 0
             */
            score_recency: number;
            /**
             * Score Interaction
             * @default 0
             */
            score_interaction: number;
            /**
             * Score Final
             * @default 0
             */
            score_final: number;
        };
        /** SkillCreate */
        SkillCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Prompt Template */
            prompt_template: string;
            /** Reference Keys */
            reference_keys?: string[];
            /** Cover Key */
            cover_key?: string | null;
            /**
             * Model
             * @default wanx2.1-imageedit
             */
            model: string;
            /**
             * Function
             * @default description_edit
             */
            function: string;
            /**
             * Strength
             * @default 0.7
             */
            strength: number;
            /**
             * Is Public
             * @default false
             */
            is_public: boolean;
        };
        /** SkillOut */
        SkillOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Owner Id */
            owner_id: string | null;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Prompt Template */
            prompt_template: string;
            /** Reference Keys */
            reference_keys: string[];
            /** Cover Url */
            cover_url?: string | null;
            /** Cover Key */
            cover_key?: string | null;
            /** Model */
            model: string;
            /** Function */
            function: string;
            /** Strength */
            strength: number;
            /** Is Public */
            is_public: boolean;
            /** Is Official */
            is_official: boolean;
            /** Use Count */
            use_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SkillUpdate */
        SkillUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Prompt Template */
            prompt_template?: string | null;
            /** Reference Keys */
            reference_keys?: string[] | null;
            /** Cover Key */
            cover_key?: string | null;
            /** Model */
            model?: string | null;
            /** Function */
            function?: string | null;
            /** Strength */
            strength?: number | null;
            /** Is Public */
            is_public?: boolean | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /**
         * UploadUrlRequest
         * @description 请求 OSS 直传签名。hash 用于去重。
         */
        UploadUrlRequest: {
            /**
             * Hash
             * @description SHA-256
             */
            hash: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Mime Type
             * @default image/jpeg
             */
            mime_type: string;
        };
        /** UploadUrlResponse */
        UploadUrlResponse: {
            /** Upload Url */
            upload_url: string;
            /** Oss Key */
            oss_key: string;
            /** Headers */
            headers: {
                [key: string]: string;
            };
            /**
             * Method
             * @default PUT
             */
            method: string;
            /** Expires In */
            expires_in: number;
            /**
             * Duplicate
             * @default false
             */
            duplicate: boolean;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nickname */
            nickname: string | null;
            /** Avatar Url */
            avatar_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    live_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    wechat_login_auth_wechat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    get_upload_url_photos_upload_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadUrlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_photos_photos_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_photo_photos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_processing_status_photos_processing_status_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoProcessingStatusBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoProcessingStatusBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_photo_photos__photo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_photo_photos__photo_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_processing_status_photos__photo_id__processing_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoProcessingStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_search_index_photos__photo_id__retry_search_index_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoProcessingStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_photo_interact_photos__photo_id__interact_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoInteract"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    semantic_search_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_search_click_search_click_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchClick"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    album_fallback_search_album_fallback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlbumFallbackQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_skills_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillOut"][];
                };
            };
        };
    };
    create_skill_skills_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plaza_skills_plaza_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_skill_skills__skill_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_skill_skills__skill_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_skill_skills__skill_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_quota_skills___quota_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaInfo"];
                };
            };
        };
    };
    agent_run_agent_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_stream_agent_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_generation_photos__photo_id__generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_generation_route_generations__generation_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_generations_generations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_generation_generations__generation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_config_admin_refresh_post: {
        parameters: {
            query?: {
                /** @description 刷新原因 */
                reason?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_skills_admin_refresh_skills_post: {
        parameters: {
            query?: {
                reason?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_prompts_admin_refresh_prompts_post: {
        parameters: {
            query?: {
                reason?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registry_stats_admin_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
